version: '3'
services:
  nginx:
    container_name: ordb-nginx
    image: nginx:stable
    ports:
      - "801:80"
    volumes:
      - ./app/:/www/app
      - ./docker-config/nginx/development.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openrecipedb-nginx.rule=Host(`openrecipedb.local`)"
      - "traefik.http.routers.openrecipedb-nginx.entrypoints=web,websecure"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default
  php-fpm:
    container_name: ordb-php-fpm
    expose:
      - "9000"
    build:
      context: ./docker-config
      dockerfile: Dockerfile-fpm
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
    stdin_open: true
    command: /docker/setup.sh
    tty: true
    volumes:
      - ./app/:/www/app
      - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/:/docker
    environment:
      - APPLICATION_ENV=development
      - PHP_IDE_CONFIG=serverName=php-fpm
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
 # composer:
 #   container_name: ordb-composer
 #   restart: 'no'
 #   image: composer/composer:2
 #   command: install --ignore-platform-reqs --prefer-source --no-plugins --no-scripts --optimize-autoloader
 #   volumes:
 #     - ./app/:/app
  mysql:
    ports:
      - "33061:3306"
    expose:
      - "3306"
    container_name: ordb-mysql
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_PASSWORD: app
      MYSQL_USER: app
      MYSQL_DATABASE: app
  redis:
    expose:
      - "6379"
    container_name: ordb-redis
    image: redis:6

networks:
  traefik:
    external:
      name: traefik

