<?php

namespace DoctrineORMModule\Proxy\__CG__\ApiSkeletons\OAuth2\Doctrine\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \ApiSkeletons\OAuth2\Doctrine\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'clientId', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'secret', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'redirectUri', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'grantType', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'clientScope', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'accessToken', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'refreshToken', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'authorizationCode', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'jwt', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'jti', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'publicKey', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'scope', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'clientId', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'secret', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'redirectUri', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'grantType', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'clientScope', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'accessToken', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'refreshToken', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'authorizationCode', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'jwt', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'jti', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'publicKey', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'scope', '' . "\0" . 'ApiSkeletons\\OAuth2\\Doctrine\\Entity\\Client' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray(array $array)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', [$array]);

        return parent::exchangeArray($array);
    }

    /**
     * {@inheritDoc}
     */
    public function setClientId($clientId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientId', [$clientId]);

        return parent::setClientId($clientId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientId', []);

        return parent::getClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecret($secret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecret', [$secret]);

        return parent::setSecret($secret);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecret', []);

        return parent::getSecret();
    }

    /**
     * {@inheritDoc}
     */
    public function setRedirectUri($redirectUri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRedirectUri', [$redirectUri]);

        return parent::setRedirectUri($redirectUri);
    }

    /**
     * {@inheritDoc}
     */
    public function getRedirectUri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedirectUri', []);

        return parent::getRedirectUri();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrantType($grantType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrantType', [$grantType]);

        return parent::setGrantType($grantType);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrantType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrantType', []);

        return parent::getGrantType();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientScope($clientScope)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientScope', [$clientScope]);

        return parent::setClientScope($clientScope);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientScope()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientScope', []);

        return parent::getClientScope();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addAccessToken(\ApiSkeletons\OAuth2\Doctrine\Entity\AccessToken $accessToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccessToken', [$accessToken]);

        return parent::addAccessToken($accessToken);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccessToken(\ApiSkeletons\OAuth2\Doctrine\Entity\AccessToken $accessToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccessToken', [$accessToken]);

        return parent::removeAccessToken($accessToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessToken', []);

        return parent::getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    public function addRefreshToken(\ApiSkeletons\OAuth2\Doctrine\Entity\RefreshToken $refreshToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRefreshToken', [$refreshToken]);

        return parent::addRefreshToken($refreshToken);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRefreshToken(\ApiSkeletons\OAuth2\Doctrine\Entity\RefreshToken $refreshToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRefreshToken', [$refreshToken]);

        return parent::removeRefreshToken($refreshToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefreshToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefreshToken', []);

        return parent::getRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    public function addAuthorizationCode(\ApiSkeletons\OAuth2\Doctrine\Entity\AuthorizationCode $authorizationCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAuthorizationCode', [$authorizationCode]);

        return parent::addAuthorizationCode($authorizationCode);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAuthorizationCode(\ApiSkeletons\OAuth2\Doctrine\Entity\AuthorizationCode $authorizationCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAuthorizationCode', [$authorizationCode]);

        return parent::removeAuthorizationCode($authorizationCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorizationCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorizationCode', []);

        return parent::getAuthorizationCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addJwt(\ApiSkeletons\OAuth2\Doctrine\Entity\Jwt $jwt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJwt', [$jwt]);

        return parent::addJwt($jwt);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJwt(\ApiSkeletons\OAuth2\Doctrine\Entity\Jwt $jwt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJwt', [$jwt]);

        return parent::removeJwt($jwt);
    }

    /**
     * {@inheritDoc}
     */
    public function getJwt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJwt', []);

        return parent::getJwt();
    }

    /**
     * {@inheritDoc}
     */
    public function addJti(\ApiSkeletons\OAuth2\Doctrine\Entity\Jti $jti)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJti', [$jti]);

        return parent::addJti($jti);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJti(\ApiSkeletons\OAuth2\Doctrine\Entity\Jti $jti)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJti', [$jti]);

        return parent::removeJti($jti);
    }

    /**
     * {@inheritDoc}
     */
    public function getJti()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJti', []);

        return parent::getJti();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicKey', []);

        return parent::getPublicKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicKey(\ApiSkeletons\OAuth2\Doctrine\Entity\PublicKey $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicKey', [$value]);

        return parent::setPublicKey($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addScope(\ApiSkeletons\OAuth2\Doctrine\Entity\Scope $scope)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addScope', [$scope]);

        return parent::addScope($scope);
    }

    /**
     * {@inheritDoc}
     */
    public function removeScope(\ApiSkeletons\OAuth2\Doctrine\Entity\Scope $scope)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeScope', [$scope]);

        return parent::removeScope($scope);
    }

    /**
     * {@inheritDoc}
     */
    public function getScope()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScope', []);

        return parent::getScope();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\ApiSkeletons\OAuth2\Doctrine\Entity\UserInterface $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

}
