<?php

/**
 * This file was autogenerated by laminas-api-tools/api-tools-mvc-auth (bin/api-tools-mvc-auth-oauth2-override.php),
 * and overrides the Laminas\ApiTools\OAuth2\Service\OAuth2Server to provide the ability to create named
 * OAuth2\Server instances.
 */

use Laminas\ApiTools\MvcAuth\Factory\NamedOAuth2ServerFactory;
return [
    'service_manager' => [
        'factories' => [
//            OAuth2Server::class => NamedOAuth2ServerFactory::class,

        ],
    ],
    'api-tools-mvc-auth' => array(
        'authentication' => array(
            'types' => [
                'api-token'
            ],
            'adapters' => array(
                'api-token' => [
                    'adapter' => 'OpenRecipeDBServer\\Authentication\\ApiKeyAuthAdapter',

                ],
            ),
        ),
    ),
];
